# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 07:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'Category_ID')),
                ('name', models.TextField(verbose_name=b'Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'Notice_ID')),
                ('branch', models.CharField(max_length=30, verbose_name=b'Branch')),
                ('course', models.CharField(max_length=50, verbose_name=b'Course')),
                ('sem', models.IntegerField(verbose_name=b'Semester')),
                ('year', models.IntegerField(verbose_name=b'Year')),
                ('date', models.DateTimeField(default=datetime.datetime.today, verbose_name=b'Date')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name=b'Time')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notifications.Category')),
            ],
        ),
    ]
