# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='Sample', max_length=140, verbose_name=b'Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'Category Name'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sem',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Semester'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Year'),
        ),
    ]
