# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0002_auto_20170209_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=b'/Notifications/Notice_images/', verbose_name=b'Notice Image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'Branch'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Course'),
        ),
    ]
