# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20170209_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(upload_to=b'/Notifications/Notice_images/', verbose_name=b'Notice Image'),
        ),
    ]
