# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0006_auto_20170209_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Category_ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='nid',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Notice_ID'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice_image',
            field=models.ImageField(upload_to='static/Notifications/Notice_images/', verbose_name='Notice Image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='sem',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
